import java.util.List;
import java.util.Map;

/** Datos del juego: escudos de las selecciones y los mejores jugadores de cada una. */
public class Datos {

    /** Escudo de cada selección: ruta en src/ o URL remota (las que empiezan por http). */
    public static final Map<String, String> ESCUDOS = Map.ofEntries(
            Map.entry("España", "/imagenes/escudos/espana.png"),
            Map.entry("Argentina", "/imagenes/escudos/argentina.png"),
            Map.entry("Francia", "/imagenes/escudos/francia.png"),
            Map.entry("Inglaterra", "/imagenes/escudos/inglaterra.png"),
            Map.entry("Brasil", "/imagenes/escudos/brasil.png"),
            Map.entry("Marruecos", "/imagenes/escudos/marruecos.png"),
            Map.entry("Portugal", "/imagenes/escudos/portugal.png"),
            Map.entry("Bélgica", "/imagenes/escudos/belgica.png"),
            Map.entry("Países Bajos", "/imagenes/escudos/paisesbajos.png"),
            Map.entry("México", "/imagenes/escudos/mexico.png"),
            Map.entry("Colombia", "/imagenes/escudos/colombia.png"),
            Map.entry("Alemania", "/imagenes/escudos/alemania.png"),
            Map.entry("Croacia", "/imagenes/escudos/croacia.png"),
            Map.entry("Suiza", "https://thumb.wikimedia.org/wikipedia/en/thumb/a/a0/Swiss_Football_Association_logo.svg/500px-Swiss_Football_Association_logo.svg.png"),
            Map.entry("Italia", "/imagenes/escudos/italia.png"),
            Map.entry("Estados Unidos", "/imagenes/escudos/usa.png"),
            Map.entry("Japón", "/imagenes/escudos/japon.png"),
            Map.entry("Senegal", "/imagenes/escudos/senegal.png"),
            Map.entry("Noruega", "/imagenes/escudos/noruega.png"),
            Map.entry("Uruguay", "/imagenes/escudos/uruguay.png")
    );

    /** Los mejores jugadores de las 20 selecciones del ranking FIFA (julio 2026). */
    public static final List<Jugador> JUGADORES = List.of(
            // España
            new Jugador("Unai Simón", "España", "España", "PORTERO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Unai_Simon_Argentina_v_Spain_19_July_2026-078_%28cropped%29.jpg/330px-Unai_Simon_Argentina_v_Spain_19_July_2026-078_%28cropped%29.jpg", "La Liga"),
            new Jugador("David Raya", "España", "España", "PORTERO", 5, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/David_Raya_Argentina_v_Spain_19_July_2026-003_%28cropped%29.jpg/330px-David_Raya_Argentina_v_Spain_19_July_2026-003_%28cropped%29.jpg", "Premier League"),
            new Jugador("Marc Cucurella", "España", "España", "DEFENSA", 5, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Marc_Cucurella_Argentina_v_Spain_19_July_2026-064_%28cropped%29.jpg/330px-Marc_Cucurella_Argentina_v_Spain_19_July_2026-064_%28cropped%29.jpg", "La Liga"),
            new Jugador("Pau Cubarsí", "España", "España", "DEFENSA", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Pau_Cubarsi_Argentina_v_Spain_19_July_2026-181_%28cropped%29.jpg/330px-Pau_Cubarsi_Argentina_v_Spain_19_July_2026-181_%28cropped%29.jpg", "La Liga"),
            new Jugador("Rodri", "España", "España", "MEDIO", 14, 93,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Rodri_Argentina_v_Spain_19_July_2026-187_%28cropped%29.jpg/330px-Rodri_Argentina_v_Spain_19_July_2026-187_%28cropped%29.jpg", "La Liga"),
            new Jugador("Pedri", "España", "España", "MEDIO", 11, 87,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Pedri_France_v_Spain_7.24.26-245.jpg/330px-Pedri_France_v_Spain_7.24.26-245.jpg", "La Liga"),
            new Jugador("Lamine Yamal", "España", "España", "DELANTERO", 16, 95,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Lamine_Yamal_France_v_Spain_7.24.26-142.jpg/330px-Lamine_Yamal_France_v_Spain_7.24.26-142.jpg", "La Liga"),
            new Jugador("Nico Williams", "España", "España", "DELANTERO", 9, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Nico_Williams_Argentina_v_Spain_19_July_2026-196_%28cropped%29.jpg/330px-Nico_Williams_Argentina_v_Spain_19_July_2026-196_%28cropped%29.jpg", "La Liga"),
            // Argentina
            new Jugador("Emiliano Martínez", "Argentina", "Argentina", "PORTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/Emiliano_Martinez_Argentina_v_Spain_19_July_2026-269.jpg/330px-Emiliano_Martinez_Argentina_v_Spain_19_July_2026-269.jpg", "Premier League"),
            new Jugador("Gerónimo Rulli", "Argentina", "Argentina", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Geronimo_Rulli_Argentina_v_Spain_19_July_2026-267_%28cropped%29.jpg/330px-Geronimo_Rulli_Argentina_v_Spain_19_July_2026-267_%28cropped%29.jpg", "Premier League"),
            new Jugador("Cristian Romero", "Argentina", "Argentina", "DEFENSA", 8, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Cristian_Romero_Argentina_v_Egypt_7_July_2026-108.jpg/330px-Cristian_Romero_Argentina_v_Egypt_7_July_2026-108.jpg", "La Liga"),
            new Jugador("Lisandro Martínez", "Argentina", "Argentina", "DEFENSA", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Lisandro_Martinez_Argentina_v_Egypt_7_July_2026-343_%28cropped%29.jpg/330px-Lisandro_Martinez_Argentina_v_Egypt_7_July_2026-343_%28cropped%29.jpg", "Premier League"),
            new Jugador("Alexis Mac Allister", "Argentina", "Argentina", "MEDIO", 9, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Alexis_Mac_Allister_Argentina_v_Spain_19_July_2026-162_%28cropped%29.jpg/330px-Alexis_Mac_Allister_Argentina_v_Spain_19_July_2026-162_%28cropped%29.jpg", "Premier League"),
            new Jugador("Enzo Fernández", "Argentina", "Argentina", "MEDIO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Enzo_Fernandez_Argentina_v_Spain_19_July_2026-050_%28cropped%29.jpg/330px-Enzo_Fernandez_Argentina_v_Spain_19_July_2026-050_%28cropped%29.jpg", "Premier League"),
            new Jugador("Lautaro Martínez", "Argentina", "Argentina", "DELANTERO", 11, 90,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Lautaro_Martinez_Argentina_v_Spain_19_July_2026-049_%28cropped%29.jpg/330px-Lautaro_Martinez_Argentina_v_Spain_19_July_2026-049_%28cropped%29.jpg", "Serie A"),
            new Jugador("Julián Álvarez", "Argentina", "Argentina", "DELANTERO", 9, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Julian_Alvarez_Argentina_v_Spain_19_July_2026-052_%28cropped%29.jpg/330px-Julian_Alvarez_Argentina_v_Spain_19_July_2026-052_%28cropped%29.jpg", "La Liga"),
            // Francia
            new Jugador("Mike Maignan", "Francia", "Francia", "PORTERO", 9, 87,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Mike_Maignan_France_v_Norway_26_June_26-132_%28cropped%29.jpg/330px-Mike_Maignan_France_v_Norway_26_June_26-132_%28cropped%29.jpg", "Serie A"),
            new Jugador("Lucas Chevalier", "Francia", "Francia", "PORTERO", 5, 73,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Chevalier_ASSE_losc_2425_%28cropped%29.jpg/330px-Chevalier_ASSE_losc_2425_%28cropped%29.jpg", "Ligue 1"),
            new Jugador("William Saliba", "Francia", "Francia", "DEFENSA", 10, 89,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/William_Saliba_France_v_Paraguay_4_July_2026-183.jpg/330px-William_Saliba_France_v_Paraguay_4_July_2026-183.jpg", "Premier League"),
            new Jugador("Théo Hernández", "Francia", "Francia", "DEFENSA", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Theo_Hernandez_France_v_Senegal_16_June_2026-222_%28cropped%29.jpg/330px-Theo_Hernandez_France_v_Senegal_16_June_2026-222_%28cropped%29.jpg", "Saudi Pro League"),
            new Jugador("Aurélien Tchouaméni", "Francia", "Francia", "MEDIO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Aurelien_Tchouameni_France_v_Senegal_16_June_2026-447_%28cropped%29.jpg/330px-Aurelien_Tchouameni_France_v_Senegal_16_June_2026-447_%28cropped%29.jpg", "La Liga"),
            new Jugador("Eduardo Camavinga", "Francia", "Francia", "MEDIO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Ofrenda_de_la_Liga_y_la_Champions-13-L.Mill%C3%A1n_%2852109790215%29_%28cropped%29.jpg/330px-Ofrenda_de_la_Liga_y_la_Champions-13-L.Mill%C3%A1n_%2852109790215%29_%28cropped%29.jpg", "La Liga"),
            new Jugador("Kylian Mbappé", "Francia", "Francia", "DELANTERO", 16, 97,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg/330px-Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg", "La Liga"),
            new Jugador("Ousmane Dembélé", "Francia", "Francia", "DELANTERO", 14, 93,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Ousmane_Dembele_France_v_Senegal_16_June_2026-341_%28cropped%29_2.jpg/330px-Ousmane_Dembele_France_v_Senegal_16_June_2026-341_%28cropped%29_2.jpg", "Ligue 1"),
            // Inglaterra
            new Jugador("Jordan Pickford", "Inglaterra", "Inglaterra", "PORTERO", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Jordan_Pickford_England_v_Ghana_23_June_2026-316_%28cropped%29.jpg/330px-Jordan_Pickford_England_v_Ghana_23_June_2026-316_%28cropped%29.jpg", "Premier League"),
            new Jugador("James Trafford", "Inglaterra", "Inglaterra", "PORTERO", 4, 71,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1d/James_Trafford_England_v_Ghana_23_June_2026-027.jpg/330px-James_Trafford_England_v_Ghana_23_June_2026-027.jpg", "Premier League"),
            new Jugador("Marc Guéhi", "Inglaterra", "Inglaterra", "DEFENSA", 7, 82,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Marc_Guehi_England_v_Panama_27_June_26-182.jpg/330px-Marc_Guehi_England_v_Panama_27_June_26-182.jpg", "Premier League"),
            new Jugador("Trent Alexander-Arnold", "Inglaterra", "Inglaterra", "DEFENSA", 9, 86,
                    "https://upload.wikimedia.org/wikipedia/commons/5/5d/Trent_Alexander-Arnold_2018_%28cropped%29.jpg", "La Liga"),
            new Jugador("Jude Bellingham", "Inglaterra", "Inglaterra", "MEDIO", 15, 92,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg/330px-Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg", "La Liga"),
            new Jugador("Declan Rice", "Inglaterra", "Inglaterra", "MEDIO", 10, 88,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Declan_Rice_England_v_Ghana_23_June_2026-150.jpg/330px-Declan_Rice_England_v_Ghana_23_June_2026-150.jpg", "Premier League"),
            new Jugador("Harry Kane", "Inglaterra", "Inglaterra", "DELANTERO", 15, 94,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg/330px-Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg", "Bundesliga"),
            new Jugador("Bukayo Saka", "Inglaterra", "Inglaterra", "DELANTERO", 12, 88,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Bukayo_Saka_England_v_Ghana_23_June_2026-057_%28cropped%29.jpg/330px-Bukayo_Saka_England_v_Ghana_23_June_2026-057_%28cropped%29.jpg", "Premier League"),
            // Brasil
            new Jugador("Alisson", "Brasil", "Brasil", "PORTERO", 8, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_%28cropped%29.jpg/330px-Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_%28cropped%29.jpg", "Premier League"),
            new Jugador("Ederson", "Brasil", "Brasil", "PORTERO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Ederson_Brazil_V_Morocco_13_June_2026-14_%28cropped%29.jpg/330px-Ederson_Brazil_V_Morocco_13_June_2026-14_%28cropped%29.jpg", "Süper Lig"),
            new Jugador("Gabriel Magalhães", "Brasil", "Brasil", "DEFENSA", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/Gabriel_Magalhaes_Brazil_V_Morocco_13_June_2026-132_%28cropped%29.jpg/330px-Gabriel_Magalhaes_Brazil_V_Morocco_13_June_2026-132_%28cropped%29.jpg", "Premier League"),
            new Jugador("Marquinhos", "Brasil", "Brasil", "DEFENSA", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Marquinhos_Brazil_V_Morocco_13_June_2026-153_%28cropped%29.jpg/330px-Marquinhos_Brazil_V_Morocco_13_June_2026-153_%28cropped%29.jpg", "Ligue 1"),
            new Jugador("Bruno Guimarães", "Brasil", "Brasil", "MEDIO", 9, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Bruno_Guimaraes_Brazil_V_Morocco_13_June_2026-78_%28cropped%29.jpg/330px-Bruno_Guimaraes_Brazil_V_Morocco_13_June_2026-78_%28cropped%29.jpg", "Premier League"),
            new Jugador("Lucas Paquetá", "Brasil", "Brasil", "MEDIO", 6, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Lucas_Paqueta_Brazil_V_Morocco_13_June_2026-134_%28cropped%29.jpg/330px-Lucas_Paqueta_Brazil_V_Morocco_13_June_2026-134_%28cropped%29.jpg", "Campeonato Brasileiro Série A"),
            new Jugador("Vinícius Júnior", "Brasil", "Brasil", "DELANTERO", 15, 92,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg/330px-Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg", "La Liga"),
            new Jugador("Raphinha", "Brasil", "Brasil", "DELANTERO", 10, 87,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Raphinha_Brazil_V_Morocco_13_June_2026-133_%28cropped%29.jpg/330px-Raphinha_Brazil_V_Morocco_13_June_2026-133_%28cropped%29.jpg", "La Liga"),
            // Marruecos
            new Jugador("Yassine Bounou", "Marruecos", "Marruecos", "PORTERO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Yassine_Bounou_Brazil_V_Morocco_13_June_2026-169.jpg/330px-Yassine_Bounou_Brazil_V_Morocco_13_June_2026-169.jpg", "Saudi Pro League"),
            new Jugador("Ahmed Reda Tagnaouti", "Marruecos", "Marruecos", "PORTERO", 3, 68,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Ahmed_Reda_Tagnaouti_Morocco_v_Norway_7_June_2026-18.jpg/330px-Ahmed_Reda_Tagnaouti_Morocco_v_Norway_7_June_2026-18.jpg", "Botola Pro"),
            new Jugador("Achraf Hakimi", "Marruecos", "Marruecos", "DEFENSA", 10, 88,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg/330px-Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg", "Ligue 1"),
            new Jugador("Noussair Mazraoui", "Marruecos", "Marruecos", "DEFENSA", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Noussair_Mazraoui_France_v_Morocco_9_July_2026-125_%28cropped%29.jpg/330px-Noussair_Mazraoui_France_v_Morocco_9_July_2026-125_%28cropped%29.jpg", "Premier League"),
            new Jugador("Sofyan Amrabat", "Marruecos", "Marruecos", "MEDIO", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Sofyan_Amrabat_Brazil_V_Morocco_13_June_2026-63.jpg/330px-Sofyan_Amrabat_Brazil_V_Morocco_13_June_2026-63.jpg", "Eredivisie"),
            new Jugador("Azzedine Ounahi", "Marruecos", "Marruecos", "MEDIO", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Azzedine_Ounahi_Brazil_V_Morocco_13_June_2026-159_%28cropped%29.jpg/330px-Azzedine_Ounahi_Brazil_V_Morocco_13_June_2026-159_%28cropped%29.jpg", "Super League Greece"),
            new Jugador("Brahim Díaz", "Marruecos", "Marruecos", "DELANTERO", 8, 83,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Brahim_Diaz_Morocco_v_Norway_7_June_2026-36_%28cropped_3-4%29.jpg/330px-Brahim_Diaz_Morocco_v_Norway_7_June_2026-36_%28cropped_3-4%29.jpg", "La Liga"),
            new Jugador("Youssef En-Nesyri", "Marruecos", "Marruecos", "DELANTERO", 5, 76,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Ennesyri.jpg/330px-Ennesyri.jpg", "Saudi Pro League"),
            // Portugal
            new Jugador("Diogo Costa", "Portugal", "Portugal", "PORTERO", 7, 83,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Diogo_Costa_Croatia_v_Portugal_2_July_2026-188_%28cropped%29.jpg/330px-Diogo_Costa_Croatia_v_Portugal_2_July_2026-188_%28cropped%29.jpg", "Primeira Liga"),
            new Jugador("José Sá", "Portugal", "Portugal", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Jos%C3%A9_S%C3%A1_USMNT_v_Portugal_Mar_31_2026-185_%28cropped%29.jpg/330px-Jos%C3%A9_S%C3%A1_USMNT_v_Portugal_Mar_31_2026-185_%28cropped%29.jpg", "EFL Championship"),
            new Jugador("Rúben Dias", "Portugal", "Portugal", "DEFENSA", 8, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Diogo_Costa_Ruben_Dias_Croatia_v_Portugal_2_July_2026-181_%28cropped%29.jpg/330px-Diogo_Costa_Ruben_Dias_Croatia_v_Portugal_2_July_2026-181_%28cropped%29.jpg", "Premier League"),
            new Jugador("Nuno Mendes", "Portugal", "Portugal", "DEFENSA", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Nuno_Mendes_Croatia_v_Portugal_2_July_2026-135_%28cropped%29.jpg/330px-Nuno_Mendes_Croatia_v_Portugal_2_July_2026-135_%28cropped%29.jpg", "Ligue 1"),
            new Jugador("Vitinha", "Portugal", "Portugal", "MEDIO", 9, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/Vitinha_USMNT_v_Portugal_Mar_31_2026-50_%28cropped%29.jpg/330px-Vitinha_USMNT_v_Portugal_Mar_31_2026-50_%28cropped%29.jpg", "Ligue 1"),
            new Jugador("Bruno Fernandes", "Portugal", "Portugal", "MEDIO", 9, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg/330px-Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg", "Premier League"),
            new Jugador("Cristiano Ronaldo", "Portugal", "Portugal", "DELANTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg/330px-Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg", "Saudi Pro League"),
            new Jugador("Rafael Leão", "Portugal", "Portugal", "DELANTERO", 10, 87,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/RafaelLe%C3%A3oPortugal23.jpg/330px-RafaelLe%C3%A3oPortugal23.jpg", "Süper Lig"),
            // Países Bajos
            new Jugador("Bart Verbruggen", "Países Bajos", "Países Bajos", "PORTERO", 6, 81,
                    "https://upload.wikimedia.org/wikipedia/commons/c/cd/Bart_Verbruggen.png", "Premier League"),
            new Jugador("Mark Flekken", "Países Bajos", "Países Bajos", "PORTERO", 5, 74,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Flekken%2C_Mark_Greuther_F%C3%BCrth_15-16_WP_%28cropped%29.jpg/330px-Flekken%2C_Mark_Greuther_F%C3%BCrth_15-16_WP_%28cropped%29.jpg", "Bundesliga"),
            new Jugador("Virgil van Dijk", "Países Bajos", "Países Bajos", "DEFENSA", 9, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/20160604_AUT_NED_8876_%28cropped%29.jpg/330px-20160604_AUT_NED_8876_%28cropped%29.jpg", "Premier League"),
            new Jugador("Jurriën Timber", "Países Bajos", "Países Bajos", "DEFENSA", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/JURRIEN_TIMBER.jpg/330px-JURRIEN_TIMBER.jpg", "Premier League"),
            new Jugador("Frenkie de Jong", "Países Bajos", "Países Bajos", "MEDIO", 9, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Frenkie_De_Jong_%282025%29_%28cropped%29.png/330px-Frenkie_De_Jong_%282025%29_%28cropped%29.png", "La Liga"),
            new Jugador("Xavi Simons", "Países Bajos", "Países Bajos", "MEDIO", 9, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2672_%28Xavi_Simons%29.jpg/330px-2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2672_%28Xavi_Simons%29.jpg", "Premier League"),
            new Jugador("Cody Gakpo", "Países Bajos", "Países Bajos", "DELANTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Netherlands_v_Tunisia_2026_World_Cup_-_55373562032_%28Cody_Gakpo%29.jpg/330px-Netherlands_v_Tunisia_2026_World_Cup_-_55373562032_%28Cody_Gakpo%29.jpg", "Premier League"),
            new Jugador("Memphis Depay", "Países Bajos", "Países Bajos", "DELANTERO", 6, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Memphis_Depay_2019.jpg/330px-Memphis_Depay_2019.jpg", "Campeonato Brasileiro Série A"),
            // Bélgica
            new Jugador("Thibaut Courtois", "Bélgica", "Bélgica", "PORTERO", 9, 88,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Thibaut_Courtois_Belgium_v_USA_6_July_2026-076_%28cropped%29.jpg/330px-Thibaut_Courtois_Belgium_v_USA_6_July_2026-076_%28cropped%29.jpg", "La Liga"),
            new Jugador("Senne Lammens", "Bélgica", "Bélgica", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Senne_Lammens_USMNT_v_Belgium_Mar_28_2026-98_%28cropped%29.jpg/330px-Senne_Lammens_USMNT_v_Belgium_Mar_28_2026-98_%28cropped%29.jpg", "Premier League"),
            new Jugador("Arthur Theate", "Bélgica", "Bélgica", "DEFENSA", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Arthur_Theate_USMNT_v_Belgium_Mar_28_2026-22_%28cropped%29.jpg/330px-Arthur_Theate_USMNT_v_Belgium_Mar_28_2026-22_%28cropped%29.jpg", "Serie A"),
            new Jugador("Zeno Debast", "Bélgica", "Bélgica", "DEFENSA", 6, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/Zeno_Debast_Belgium_v_USA_6_July_2026-039_%28cropped%29.jpg/330px-Zeno_Debast_Belgium_v_USA_6_July_2026-039_%28cropped%29.jpg", "Primeira Liga"),
            new Jugador("Kevin De Bruyne", "Bélgica", "Bélgica", "MEDIO", 10, 89,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/330px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg", "Serie A"),
            new Jugador("Youri Tielemans", "Bélgica", "Bélgica", "MEDIO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Youri_Tielemans_USMNT_v_Belgium_Mar_28_2026-20_%28cropped%29.jpg/330px-Youri_Tielemans_USMNT_v_Belgium_Mar_28_2026-20_%28cropped%29.jpg", "Premier League"),
            new Jugador("Romelu Lukaku", "Bélgica", "Bélgica", "DELANTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Romelu_Lukaku_Belgium_v_USA_6_July_2026-038.jpg/330px-Romelu_Lukaku_Belgium_v_USA_6_July_2026-038.jpg", "Süper Lig"),
            new Jugador("Jérémy Doku", "Bélgica", "Bélgica", "DELANTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/J%C3%A9r%C3%A9my_Doku_USMNT_v_Belgium_Mar_28_2026-27_%28cropped%29.jpg/330px-J%C3%A9r%C3%A9my_Doku_USMNT_v_Belgium_Mar_28_2026-27_%28cropped%29.jpg", "Premier League"),
            // México
            new Jugador("Luis Malagón", "México", "México", "PORTERO", 5, 75,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/%C3%81ngel_Malag%C3%B3n_2.png/330px-%C3%81ngel_Malag%C3%B3n_2.png", "Liga MX"),
            new Jugador("Carlos Acevedo", "México", "México", "PORTERO", 3, 68,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Carlos_Acevedo.png/330px-Carlos_Acevedo.png", "Liga MX"),
            new Jugador("César Montes", "México", "México", "DEFENSA", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a9/C%C3%A9sar_Montes.png/330px-C%C3%A9sar_Montes.png", "Russian Premier League"),
            new Jugador("Johan Vásquez", "México", "México", "DEFENSA", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Johan_V%C3%A1squez.png/330px-Johan_V%C3%A1squez.png", "Serie A"),
            new Jugador("Edson Álvarez", "México", "México", "MEDIO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Edson_%C3%81lvarez.png/330px-Edson_%C3%81lvarez.png", "EFL Championship"),
            new Jugador("Luis Chávez", "México", "México", "MEDIO", 6, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Luis_Ch%C3%A1vez_WC_2022_-_01.jpg/330px-Luis_Ch%C3%A1vez_WC_2022_-_01.jpg", "Russian Premier League"),
            new Jugador("Santiago Giménez", "México", "México", "DELANTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Santiago_Gim%C3%A9nez.png/330px-Santiago_Gim%C3%A9nez.png", "Primeira Liga"),
            new Jugador("Raúl Jiménez", "México", "México", "DELANTERO", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Ra%C3%BAl_Jim%C3%A9nez_04032026_%281%29.jpg/330px-Ra%C3%BAl_Jim%C3%A9nez_04032026_%281%29.jpg", "EFL Championship"),
            // Colombia
            new Jugador("Camilo Vargas", "Colombia", "Colombia", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Camilo_Andres_Vargas.jpg/330px-Camilo_Andres_Vargas.jpg", "Liga MX"),
            new Jugador("Álvaro Montero", "Colombia", "Colombia", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Alvaro_montero_in_2024.jpg/330px-Alvaro_montero_in_2024.jpg", "Argentine Primera División"),
            new Jugador("Davinson Sánchez", "Colombia", "Colombia", "DEFENSA", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/D%C3%A1vinson_S%C3%A1nchez%2C_Colombia_NT_presidential_send-off%2C_Jun_2026.jpg/330px-D%C3%A1vinson_S%C3%A1nchez%2C_Colombia_NT_presidential_send-off%2C_Jun_2026.jpg", "Süper Lig"),
            new Jugador("Daniel Muñoz", "Colombia", "Colombia", "DEFENSA", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Daniel_Mu%C3%B1oz%2C_Colombia_NT_presidential_send-off%2C_Jun_2026.jpg/330px-Daniel_Mu%C3%B1oz%2C_Colombia_NT_presidential_send-off%2C_Jun_2026.jpg", "Premier League"),
            new Jugador("Jefferson Lerma", "Colombia", "Colombia", "MEDIO", 5, 75,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Jefferson_Lerma_2018.png/330px-Jefferson_Lerma_2018.png", "Premier League"),
            new Jugador("Richard Ríos", "Colombia", "Colombia", "MEDIO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Richard_Rios_2026.jpg/330px-Richard_Rios_2026.jpg", "Saudi Pro League"),
            new Jugador("Luis Díaz", "Colombia", "Colombia", "DELANTERO", 11, 89,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_40_%28Luiz_D%C3%ADaz%29.jpg/330px-FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_40_%28Luiz_D%C3%ADaz%29.jpg", "Bundesliga"),
            new Jugador("Jhon Durán", "Colombia", "Colombia", "DELANTERO", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/Jhon_Dur%C3%A1n%2C_Esteghlal_FC_vs_Al-Nassr_FC_%28ACLElite%29%3B_3_Mar_2025.png/330px-Jhon_Dur%C3%A1n%2C_Esteghlal_FC_vs_Al-Nassr_FC_%28ACLElite%29%3B_3_Mar_2025.png", "Primeira Liga"),
            // Alemania
            new Jugador("Marc-André ter Stegen", "Alemania", "Alemania", "PORTERO", 8, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Marc-Andre_Ter_Stegen_ACCI_FCBARCELONA_Turisme_Catalunya_gira_pretemporada_CATPRESS.jpg/330px-Marc-Andre_Ter_Stegen_ACCI_FCBARCELONA_Turisme_Catalunya_gira_pretemporada_CATPRESS.jpg", "Eredivisie"),
            new Jugador("Oliver Baumann", "Alemania", "Alemania", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Oliver_Baumann_Ecuador_v_Germany_25_June_2026-066.jpg/330px-Oliver_Baumann_Ecuador_v_Germany_25_June_2026-066.jpg", "Bundesliga"),
            new Jugador("Jonathan Tah", "Alemania", "Alemania", "DEFENSA", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Jonathan_Tah_Ecuador_v_Germany_25_June_2026-116.jpg/330px-Jonathan_Tah_Ecuador_v_Germany_25_June_2026-116.jpg", "Bundesliga"),
            new Jugador("Nico Schlotterbeck", "Alemania", "Alemania", "DEFENSA", 7, 82,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93069.jpg/330px-2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93069.jpg", "Bundesliga"),
            new Jugador("Joshua Kimmich", "Alemania", "Alemania", "MEDIO", 10, 88,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Joshua_Kimmich_Ecuador_v_Germany_25_June_2026-149.jpg/330px-Joshua_Kimmich_Ecuador_v_Germany_25_June_2026-149.jpg", "Bundesliga"),
            new Jugador("Florian Wirtz", "Alemania", "Alemania", "MEDIO", 13, 90,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Florian_Wirtz_Ecuador_v_Germany_25_June_2026-181_%28cropped%29.jpg/330px-Florian_Wirtz_Ecuador_v_Germany_25_June_2026-181_%28cropped%29.jpg", "Premier League"),
            new Jugador("Jamal Musiala", "Alemania", "Alemania", "DELANTERO", 14, 91,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/Jamal_Musiala_Ecuador_v_Germany_25_June_2026-174_%28cropped%29.jpg/330px-Jamal_Musiala_Ecuador_v_Germany_25_June_2026-174_%28cropped%29.jpg", "Bundesliga"),
            new Jugador("Kai Havertz", "Alemania", "Alemania", "DELANTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Kai_Havertz_Ecuador_v_Germany_25_June_2026-118.jpg/330px-Kai_Havertz_Ecuador_v_Germany_25_June_2026-118.jpg", "Premier League"),
            // Croacia
            new Jugador("Dominik Livaković", "Croacia", "Croacia", "PORTERO", 5, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Dominik_Livakovic_Croatia_v_Portugal_2_July_2026-063.jpg/330px-Dominik_Livakovic_Croatia_v_Portugal_2_July_2026-063.jpg", "La Liga"),
            new Jugador("Dominik Kotarski", "Croacia", "Croacia", "PORTERO", 3, 66,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Dominik_Kotarski_Croatia_v_Portugal_2_July_2026-012.jpg/330px-Dominik_Kotarski_Croatia_v_Portugal_2_July_2026-012.jpg", "Danish Superliga"),
            new Jugador("Joško Gvardiol", "Croacia", "Croacia", "DEFENSA", 10, 87,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Josko_Gvardiol_Croatia_v_Portugal_2_July_2026-262.jpg/330px-Josko_Gvardiol_Croatia_v_Portugal_2_July_2026-262.jpg", "Premier League"),
            new Jugador("Josip Stanišić", "Croacia", "Croacia", "DEFENSA", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Josip_Stanisic_Croatia_v_Portugal_2_July_2026-022.jpg/330px-Josip_Stanisic_Croatia_v_Portugal_2_July_2026-022.jpg", "Bundesliga"),
            new Jugador("Luka Modrić", "Croacia", "Croacia", "MEDIO", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg/330px-Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg", "Serie A"),
            new Jugador("Mateo Kovačić", "Croacia", "Croacia", "MEDIO", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Mateo_Kovacic_Croatia_v_Portugal_2_July_2026-132.jpg/330px-Mateo_Kovacic_Croatia_v_Portugal_2_July_2026-132.jpg", "Premier League"),
            new Jugador("Andrej Kramarić", "Croacia", "Croacia", "DELANTERO", 5, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Andrej_Kramaric_Croatia_v_Portugal_2_July_2026-014.jpg/330px-Andrej_Kramaric_Croatia_v_Portugal_2_July_2026-014.jpg", "Bundesliga"),
            new Jugador("Bruno Petković", "Croacia", "Croacia", "DELANTERO", 4, 73,
                    "https://upload.wikimedia.org/wikipedia/commons/0/00/Bruno-Petkovic.png", "Süper Lig"),
            // Suiza
            new Jugador("Gregor Kobel", "Suiza", "Suiza", "PORTERO", 6, 82,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93090.jpg/330px-2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93090.jpg", "Bundesliga"),
            new Jugador("Jonas Omlin", "Suiza", "Suiza", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Jonas_Omlin_2019.jpg/330px-Jonas_Omlin_2019.jpg", "Swiss Super League"),
            new Jugador("Manuel Akanji", "Suiza", "Suiza", "DEFENSA", 7, 83,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2792_%28Manuel_Akanji%29.jpg/330px-2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2792_%28Manuel_Akanji%29.jpg", "Serie A"),
            new Jugador("Nico Elvedi", "Suiza", "Suiza", "DEFENSA", 5, 78,
                    "https://upload.wikimedia.org/wikipedia/commons/0/0e/Wales-Switzerland_match_at_Euro_2020_in_Baku_%28cropped%29.jpg", "Premier League"),
            new Jugador("Granit Xhaka", "Suiza", "Suiza", "MEDIO", 8, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Granit_Xhaka_%28cropped%29.jpg/330px-Granit_Xhaka_%28cropped%29.jpg", "Premier League"),
            new Jugador("Denis Zakaria", "Suiza", "Suiza", "MEDIO", 4, 73,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Zakaria_asse_asm_2425_%28cropped%29.png/330px-Zakaria_asse_asm_2425_%28cropped%29.png", "Ligue 1"),
            new Jugador("Breel Embolo", "Suiza", "Suiza", "DELANTERO", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/2022128160447_2022-05-08_Fussball_Eintracht_Frankfurt_vs_Borussia_M%C3%B6nchengladbach_-_Sven_-_1D_X_MK_II_-_1422_-_B70I7533_%28cropped%29.jpg/330px-2022128160447_2022-05-08_Fussball_Eintracht_Frankfurt_vs_Borussia_M%C3%B6nchengladbach_-_Sven_-_1D_X_MK_II_-_1422_-_B70I7533_%28cropped%29.jpg", "Major League Soccer"),
            new Jugador("Dan Ndoye", "Suiza", "Suiza", "DELANTERO", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Lens_-_Nice_%2823-01-2021%29_52.jpg/330px-Lens_-_Nice_%2823-01-2021%29_52.jpg", "Premier League"),
            // Italia
            new Jugador("Gianluigi Donnarumma", "Italia", "Italia", "PORTERO", 8, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Norway_Italy_-_June_2025_A_17_%28Gianluigi_Donnarumma%29.jpg/330px-Norway_Italy_-_June_2025_A_17_%28Gianluigi_Donnarumma%29.jpg", "Premier League"),
            new Jugador("Guglielmo Vicario", "Italia", "Italia", "PORTERO", 5, 75,
                    "https://upload.wikimedia.org/wikipedia/commons/f/f1/Guglielmo_Vicario.png", "Serie A"),
            new Jugador("Alessandro Bastoni", "Italia", "Italia", "DEFENSA", 8, 86,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Norway_Italy_-_June_2025_A_36_%28cropped%29.jpg/330px-Norway_Italy_-_June_2025_A_36_%28cropped%29.jpg", "Serie A"),
            new Jugador("Riccardo Calafiori", "Italia", "Italia", "DEFENSA", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/1_Riccardo_Calafiori_2026_%28cropped%29.jpg/330px-1_Riccardo_Calafiori_2026_%28cropped%29.jpg", "Premier League"),
            new Jugador("Nicolò Barella", "Italia", "Italia", "MEDIO", 9, 87,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Nicol%C3%B2_Barella_in_2021_%28cropped_2%29.jpg/330px-Nicol%C3%B2_Barella_in_2021_%28cropped_2%29.jpg", "Serie A"),
            new Jugador("Sandro Tonali", "Italia", "Italia", "MEDIO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Norway_Italy_-_June_2025_B_03.jpg/330px-Norway_Italy_-_June_2025_B_03.jpg", "Premier League"),
            new Jugador("Moise Kean", "Italia", "Italia", "DELANTERO", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/FC_Zenit_Saint_Petersburg_vs._Juventus%2C_20_October_2021_64_-_Moise_Kean_%28cropped%29.jpg/330px-FC_Zenit_Saint_Petersburg_vs._Juventus%2C_20_October_2021_64_-_Moise_Kean_%28cropped%29.jpg", "Serie A"),
            new Jugador("Federico Chiesa", "Italia", "Italia", "DELANTERO", 7, 82,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Federico_Chiesa_vs_Zenit_2021-10-20_%28cropped2%29.jpg/330px-Federico_Chiesa_vs_Zenit_2021-10-20_%28cropped2%29.jpg", "Premier League"),
            // Estados Unidos
            new Jugador("Matt Turner", "Estados Unidos", "Estados Unidos", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Matt_Turner_Australia_v_USA_19_June_2026-46_%28cropped%29.jpg/330px-Matt_Turner_Australia_v_USA_19_June_2026-46_%28cropped%29.jpg", "Major League Soccer"),
            new Jugador("Matt Freese", "Estados Unidos", "Estados Unidos", "PORTERO", 3, 66,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Matt_Freese_NYCFC_v_Cincinnati_22_Apr_26-40_%28cropped%29.jpg/330px-Matt_Freese_NYCFC_v_Cincinnati_22_Apr_26-40_%28cropped%29.jpg", "Major League Soccer"),
            new Jugador("Chris Richards", "Estados Unidos", "Estados Unidos", "DEFENSA", 5, 75,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Chris_Richards_Australia_v_USA_19_June_2026-54_%28cropped%29.jpg/330px-Chris_Richards_Australia_v_USA_19_June_2026-54_%28cropped%29.jpg", "Premier League"),
            new Jugador("Antonee Robinson", "Estados Unidos", "Estados Unidos", "DEFENSA", 5, 75,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Antonee_Robinson_Australia_v_USA_19_June_2026-24_%28cropped%29.jpg/330px-Antonee_Robinson_Australia_v_USA_19_June_2026-24_%28cropped%29.jpg", "Premier League"),
            new Jugador("Yunus Musah", "Estados Unidos", "Estados Unidos", "MEDIO", 6, 79,
                    "https://upload.wikimedia.org/wikipedia/commons/d/dc/2022_FIFA_World_Cup_United_States_1%E2%80%931_Wales_-_%2813%29_%28cropped%29.jpg", "Serie A"),
            new Jugador("Malik Tillman", "Estados Unidos", "Estados Unidos", "MEDIO", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Malik_Tillman_Australia_v_USA_19_June_2026-143_%28cropped%29.jpg/330px-Malik_Tillman_Australia_v_USA_19_June_2026-143_%28cropped%29.jpg", "Bundesliga"),
            new Jugador("Christian Pulisic", "Estados Unidos", "Estados Unidos", "DELANTERO", 8, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg/330px-Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg", "Serie A"),
            new Jugador("Folarin Balogun", "Estados Unidos", "Estados Unidos", "DELANTERO", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Folarin_Balogun_Australia_v_USA_19_June_2026-64.jpg/330px-Folarin_Balogun_Australia_v_USA_19_June_2026-64.jpg", "Ligue 1"),
            // Japón
            new Jugador("Zion Suzuki", "Japón", "Japón", "PORTERO", 5, 74,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/ZION_SUZUKI_-_JPN_vs_THA_-_Friendly_Match_-_2024.01.01.jpg/330px-ZION_SUZUKI_-_JPN_vs_THA_-_Friendly_Match_-_2024.01.01.jpg", "Premier League"),
            new Jugador("Tomoki Hayakawa", "Japón", "Japón", "PORTERO", 3, 66,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/J1League-Football-2026-2027---YokohamaFM-and-Kashima---2026-08-07_00057_%28cropped%29-Tomoki-Hayakawa.jpg/330px-J1League-Football-2026-2027---YokohamaFM-and-Kashima---2026-08-07_00057_%28cropped%29-Tomoki-Hayakawa.jpg", "J1 League"),
            new Jugador("Hiroki Itō", "Japón", "Japón", "DEFENSA", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Hiroki_Ito_VfB_Stuttgart.jpg/330px-Hiroki_Ito_VfB_Stuttgart.jpg", "Bundesliga"),
            new Jugador("Takehiro Tomiyasu", "Japón", "Japón", "DEFENSA", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Takehiro_Tomiyasu%2C_2019_AFC_Asian_Cup_1.jpg/330px-Takehiro_Tomiyasu%2C_2019_AFC_Asian_Cup_1.jpg", "Premier League"),
            new Jugador("Daichi Kamada", "Japón", "Japón", "MEDIO", 5, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/2022128173756_2022-05-08_Fussball_Eintracht_Frankfurt_vs_Borussia_M%C3%B6nchengladbach_-_Sven_-_1D_X_MK_II_-_0725_-_AK8I7460_%28Daichi_Kamada_cropped%29.jpg/330px-2022128173756_2022-05-08_Fussball_Eintracht_Frankfurt_vs_Borussia_M%C3%B6nchengladbach_-_Sven_-_1D_X_MK_II_-_0725_-_AK8I7460_%28Daichi_Kamada_cropped%29.jpg", "Premier League"),
            new Jugador("Ritsu Dōan", "Japón", "Japón", "MEDIO", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Ritsu_Doan%2C_2019_AFC_Asian_Cup_1.jpg/330px-Ritsu_Doan%2C_2019_AFC_Asian_Cup_1.jpg", "Bundesliga"),
            new Jugador("Takefusa Kubo", "Japón", "Japón", "DELANTERO", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Takefusa_Kubo.jpg/330px-Takefusa_Kubo.jpg", "La Liga"),
            new Jugador("Kaoru Mitoma", "Japón", "Japón", "DELANTERO", 7, 82,
                    "https://upload.wikimedia.org/wikipedia/commons/6/65/Kaoru_Mitoma_2026.jpg", "Premier League"),
            // Senegal
            new Jugador("Yehvann Diouf", "Senegal", "Senegal", "PORTERO", 3, 66,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/Diouf_asse_sr_2425.png/330px-Diouf_asse_sr_2425.png", "Ligue 1"),
            new Jugador("Seny Dieng", "Senegal", "Senegal", "PORTERO", 3, 68,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/Banc_de_touche_assis_du_Senegal_%28Seny_Dieng%29.jpg/330px-Banc_de_touche_assis_du_Senegal_%28Seny_Dieng%29.jpg", "Super League Greece"),
            new Jugador("Kalidou Koulibaly", "Senegal", "Senegal", "DEFENSA", 6, 80,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Kalidou_Koulibaly_France_v_Senegal_16_June_2026-370_%28cropped%29.jpg/330px-Kalidou_Koulibaly_France_v_Senegal_16_June_2026-370_%28cropped%29.jpg", "Saudi Pro League"),
            new Jugador("Moussa Niakhaté", "Senegal", "Senegal", "DEFENSA", 5, 74,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Niakhat%C3%A9_asse_ol_2425.png/330px-Niakhat%C3%A9_asse_ol_2425.png", "Ligue 1"),
            new Jugador("Pape Gueye", "Senegal", "Senegal", "MEDIO", 6, 79,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a9/Pape_Gueye_France_v_Senegal_16_June_2026-359_%28cropped%29.jpg/330px-Pape_Gueye_France_v_Senegal_16_June_2026-359_%28cropped%29.jpg", "La Liga"),
            new Jugador("Habib Diarra", "Senegal", "Senegal", "MEDIO", 5, 74,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Diarra_asse_rcsa_2425.jpg/330px-Diarra_asse_rcsa_2425.jpg", "Premier League"),
            new Jugador("Sadio Mané", "Senegal", "Senegal", "DELANTERO", 8, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg/330px-Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg", "Saudi Pro League"),
            new Jugador("Nicolas Jackson", "Senegal", "Senegal", "DELANTERO", 7, 82,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Nicolas_Jackson_France_v_Senegal_16_June_2026-369_%28cropped%29.jpg/330px-Nicolas_Jackson_France_v_Senegal_16_June_2026-369_%28cropped%29.jpg", "Premier League"),
            // Noruega
            new Jugador("Ørjan Nyland", "Noruega", "Noruega", "PORTERO", 5, 74,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Orjan_Nyland_France_v_Norway_26_June_26-023_%28cropped%29.jpg/330px-Orjan_Nyland_France_v_Norway_26_June_26-023_%28cropped%29.jpg", "Bundesliga"),
            new Jugador("Egil Selvik", "Noruega", "Noruega", "PORTERO", 3, 69,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Norway_Italy_-_June_2025_A_07_%28cropped%29.jpg/330px-Norway_Italy_-_June_2025_A_07_%28cropped%29.jpg", "Ligue 1"),
            new Jugador("Kristoffer Ajer", "Noruega", "Noruega", "DEFENSA", 5, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/Kristoffer_Vassbakk_Ajer_France_v_Norway_26_June_26-013.jpg/330px-Kristoffer_Vassbakk_Ajer_France_v_Norway_26_June_26-013.jpg", "Premier League"),
            new Jugador("Leo Østigård", "Noruega", "Noruega", "DEFENSA", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Leo_Ostigard_Morocco_v_Norway_7_June_2026-20.jpg/330px-Leo_Ostigard_Morocco_v_Norway_7_June_2026-20.jpg", "Serie A"),
            new Jugador("Martin Ødegaard", "Noruega", "Noruega", "MEDIO", 10, 89,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Martin_Odegaard_France_v_Norway_26_June_26-014.jpg/330px-Martin_Odegaard_France_v_Norway_26_June_26-014.jpg", "Premier League"),
            new Jugador("Sander Berge", "Noruega", "Noruega", "MEDIO", 5, 77,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Sander_Berge_France_v_Norway_26_June_26-025.jpg/330px-Sander_Berge_France_v_Norway_26_June_26-025.jpg", "Premier League"),
            new Jugador("Erling Haaland", "Noruega", "Noruega", "DELANTERO", 16, 96,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/330px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg", "Premier League"),
            new Jugador("Jørgen Strand Larsen", "Noruega", "Noruega", "DELANTERO", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Jorgen_Strand_Larsen_France_v_Norway_26_June_26-152.jpg/330px-Jorgen_Strand_Larsen_France_v_Norway_26_June_26-152.jpg", "Premier League"),
            // Uruguay
            new Jugador("Sergio Rochet", "Uruguay", "Uruguay", "PORTERO", 4, 72,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/Sergio_Rochet_%282022%29.jpg/330px-Sergio_Rochet_%282022%29.jpg", "Campeonato Brasileiro Série A"),
            new Jugador("Santiago Mele", "Uruguay", "Uruguay", "PORTERO", 3, 70,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Santiago_Mele.png/330px-Santiago_Mele.png", "AFA Liga Profesional de Fútbol"),
            new Jugador("José María Giménez", "Uruguay", "Uruguay", "DEFENSA", 6, 81,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Jos%C3%A9_Mar%C3%ADa_Gim%C3%A9nez.jpg/330px-Jos%C3%A9_Mar%C3%ADa_Gim%C3%A9nez.jpg", "La Liga"),
            new Jugador("Ronald Araújo", "Uruguay", "Uruguay", "DEFENSA", 8, 84,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/FC_Red_Bull_Salzburg_gegen_CF_Barcelona_%28Testspiel_4._August_2021%29_45_%28cropped%29.jpg/330px-FC_Red_Bull_Salzburg_gegen_CF_Barcelona_%28Testspiel_4._August_2021%29_45_%28cropped%29.jpg", "Premier League"),
            new Jugador("Federico Valverde", "Uruguay", "Uruguay", "MEDIO", 10, 89,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Federico_Valverde_2021_%28cropped%29.jpg/330px-Federico_Valverde_2021_%28cropped%29.jpg", "La Liga"),
            new Jugador("Manuel Ugarte", "Uruguay", "Uruguay", "MEDIO", 6, 78,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/M.UGARTE.jpg/330px-M.UGARTE.jpg", "Premier League"),
            new Jugador("Darwin Núñez", "Uruguay", "Uruguay", "DELANTERO", 9, 85,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Darwin_N%C3%BA%C3%B1ez_%28cropped%29.jpg/330px-Darwin_N%C3%BA%C3%B1ez_%28cropped%29.jpg", "Saudi Pro League"),
            new Jugador("Facundo Pellistri", "Uruguay", "Uruguay", "DELANTERO", 5, 74,
                    "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Facundo_Pellistri_WC2022.jpg/330px-Facundo_Pellistri_WC2022.jpg", "Super League Greece")
    );
}
